title: Wenshuo Wang
logo: /assets/img/Wenshuo2.jpeg
# description: Minimal is a theme for GitHub Pages.
# show_downloads: false
university: university
email: email
github: github
googlescholar: googlescholar
google_analytics: true
navigation: true
theme: jekyll-theme-minimal
